// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReCrafted.Tools.APIGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class CPlusPlusTemplate : CPlusPlusTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// ReCrafted (c) 2016-2019 Damian \'Erdroy\' Korczowski. All rights reserved.\r\n// W" +
                    "ARNING: Auto-generated file. All changes will be lost when the API code will be " +
                    "regenerated!\r\n\r\n#include \"");
            
            #line 12 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator.Instance.InputFileName));
            
            #line default
            #line hidden
            this.Write(".h\"\r\n#include \"Scripting/Mono.h\"\r\n#include \"Scripting/ScriptingManager.h\"\r\n#inclu" +
                    "de \"Scripting/Assembly.h\"\r\n\r\nclass APIProxy\r\n{\r\npublic:\r\n");
            
            #line 20 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

foreach(var function in Functions)
{

            
            #line default
            #line hidden
            this.Write("    \r\n    static ");
            
            #line 25 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.ReturnType.ToSpecial(true)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 25 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 25 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 25 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.GetCPlusPlusParameters(Class, !function.IsStatic)));
            
            #line default
            #line hidden
            this.Write(") \r\n    {\r\n");
            
            #line 27 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    if(!function.AllowMultithread)
    {

            
            #line default
            #line hidden
            this.Write("        MAIN_THREAD_ONLY();\r\n");
            
            #line 32 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
    // ---- Special type conversions ----
    foreach(var parameter in function.Parameters)
    {
        if(parameter.Type.IsSpecial)
        {

            
            #line default
            #line hidden
            this.Write("        ASSERT(p_");
            
            #line 40 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n        const auto ");
            
            #line 41 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 41 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.GetSpecialConversion()));
            
            #line default
            #line hidden
            this.Write("(p_");
            
            #line 41 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 42 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

        }
    }

    // ---- Static function impl ----
    if(function.IsStatic)
    {
        if(function.ReturnType.BaseType != "void")
        {

            
            #line default
            #line hidden
            this.Write("        const auto _returnValue = ");
            
            #line 52 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::");
            
            #line 52 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 52 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.GetCPlusPlusParametersRedirect()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 53 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 58 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::");
            
            #line 58 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 58 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.GetCPlusPlusParametersRedirect()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 59 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
      
        }
    }
    else // ---- Member function impl ----
    {

            
            #line default
            #line hidden
            this.Write("        ASSERT(instance);\r\n");
            
            #line 66 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

        if(function.ReturnType.BaseType != "void")
        {

            
            #line default
            #line hidden
            this.Write("        const auto _returnValue = instance->");
            
            #line 70 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 70 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.GetCPlusPlusParametersRedirect()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 71 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("        instance->");
            
            #line 76 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 76 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.GetCPlusPlusParametersRedirect()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 77 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
      
        }
    }
    // ---- Special type free ----
    foreach(var parameter in function.Parameters)
    {
        if(parameter.Type.IsSpecial)
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 86 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.GetSpecialFree()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 86 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 87 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

        }
    }
    if(function.ReturnType.BaseType != "void")
    {
        if(function.ReturnType.IsSpecial)
        {

            
            #line default
            #line hidden
            this.Write("        return ");
            
            #line 95 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.ReturnType.GetSpecialReturnConversion()));
            
            #line default
            #line hidden
            this.Write("(_returnValue);\r\n");
            
            #line 96 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

        }
        else
        {
            if(function.ReturnType.CastToManaged)
            {       

            
            #line default
            #line hidden
            this.Write("        return _returnValue != nullptr ? _returnValue->ToManaged() : nullptr;\r\n");
            
            #line 104 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

            }
            else
            {       

            
            #line default
            #line hidden
            this.Write("        return _returnValue;\r\n");
            
            #line 110 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

            } 
        }
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 116 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}

foreach(var property in Properties)
{
    if(property.HasGetter)
    {

            
            #line default
            #line hidden
            this.Write("    \r\n    static void ");
            
            #line 125 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_Get_");
            
            #line 125 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 125 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.GetCPlusPlusParameter(Class, true)));
            
            #line default
            #line hidden
            this.Write(") \r\n    {\r\n");
            
            #line 127 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

if(!property.AllowMultithread)
{

            
            #line default
            #line hidden
            this.Write("        MAIN_THREAD_ONLY();\r\n");
            
            #line 132 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}
if(!property.IsStatic)
{

            
            #line default
            #line hidden
            this.Write("        ASSERT(instance);   \r\n        const auto _returnValue = ");
            
            #line 138 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
if(property.Type.CastToManaged){
            
            #line default
            #line hidden
            this.Write("instance != nullptr ? ");
            
            #line 138 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("instance->");
            
            #line 138 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.GetterFunctionName));
            
            #line default
            #line hidden
            this.Write("()");
            
            #line 138 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
if(property.Type.CastToManaged){
            
            #line default
            #line hidden
            this.Write("->ToManaged() : nullptr");
            
            #line 138 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 139 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    if(property.Type.IsSpecial)
    {

            
            #line default
            #line hidden
            this.Write("        *p_data = ");
            
            #line 143 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.GetSpecialReturnConversion()));
            
            #line default
            #line hidden
            this.Write("(_returnValue);\r\n");
            
            #line 144 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("        *data = _returnValue;\r\n");
            
            #line 150 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 155 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
    if(property.HasSetter)
    {

            
            #line default
            #line hidden
            this.Write("\r\n    static void ");
            
            #line 161 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_Set_");
            
            #line 161 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 161 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.GetCPlusPlusParameter(Class, false)));
            
            #line default
            #line hidden
            this.Write(") \r\n    {\r\n");
            
            #line 163 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

if(!property.AllowMultithread)
{

            
            #line default
            #line hidden
            this.Write("        MAIN_THREAD_ONLY();\r\n");
            
            #line 168 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}
if(property.Type.IsSpecial)
{

            
            #line default
            #line hidden
            this.Write("        ASSERT(p_data);\r\n        const auto data = ");
            
            #line 174 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.GetSpecialConversion()));
            
            #line default
            #line hidden
            this.Write("(*p_data);\r\n");
            
            #line 175 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}
if(!property.IsStatic)
{

            
            #line default
            #line hidden
            this.Write("        ASSERT(instance);\r\n        instance->");
            
            #line 181 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.SetterFunctionName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 181 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
if(!property.Type.IsSpecial){
            
            #line default
            #line hidden
            this.Write("*");
            
            #line 181 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("data);\r\n");
            
            #line 182 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}        
if(property.Type.IsSpecial)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 187 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.GetSpecialFree()));
            
            #line default
            #line hidden
            this.Write("(data);\r\n");
            
            #line 188 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 192 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
}

if(!Class.IsStatic && !string.IsNullOrEmpty(Class.Inherits) && !Class.IsAbstract)
{

            
            #line default
            #line hidden
            this.Write("    \r\n    static Object* ");
            
            #line 200 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_CreateObject(bool createManagedInstance)\r\n    {\r\n        return createManagedIns" +
                    "tance ? Object::New<");
            
            #line 202 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write(">() : new ");
            
            #line 202 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n    }\r\n");
            
            #line 204 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("};\r\n\r\nvoid ");
            
            #line 209 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::InitRuntime() \r\n{\r\n");
            
            #line 211 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

if(!Class.IsStatic && !string.IsNullOrEmpty(Class.Inherits) && !Class.IsAbstract)
{

            
            #line default
            #line hidden
            this.Write("    MONO_REGISTER_OBJECT(&APIProxy::");
            
            #line 215 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_CreateObject);\r\n    \r\n");
            
            #line 217 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}

            
            #line default
            #line hidden
            
            #line 220 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

// ---- Function bindings ----
foreach(var function in Functions)
{

            
            #line default
            #line hidden
            this.Write("    API_BIND(\"");
            
            #line 225 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 225 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::Internal");
            
            #line 225 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write("\", &APIProxy::");
            
            #line 225 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 225 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 226 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

}
foreach(var property in Properties)
{
    if(property.HasGetter)
    {

            
            #line default
            #line hidden
            this.Write("    API_BIND(\"");
            
            #line 233 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 233 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::Get_Internal");
            
            #line 233 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", &APIProxy::");
            
            #line 233 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_Get_");
            
            #line 233 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 234 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
    if(property.HasSetter)
    {

            
            #line default
            #line hidden
            this.Write("    API_BIND(\"");
            
            #line 239 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 239 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::Set_Internal");
            
            #line 239 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", &APIProxy::");
            
            #line 239 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("_Set_");
            
            #line 239 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 240 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("}\r\n\r\nconst char* ");
            
            #line 246 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::Fullname() \r\n{\r\n    return \"");
            
            #line 248 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 248 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n}\r\n\r\nconst char* ");
            
            #line 251 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::Name() \r\n{\r\n    return \"");
            
            #line 253 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n}\r\n\r\nconst char* ");
            
            #line 256 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Name));
            
            #line default
            #line hidden
            this.Write("::Namespace() \r\n{\r\n    return \"");
            
            #line 258 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Namespace));
            
            #line default
            #line hidden
            this.Write("\";\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\ReCrafted\Source\Tools\ReCrafted.Tools.APIGenerator\Templates\CPlusPlusTemplate.tt"

private global::ReCrafted.Tools.APIGenerator.Descriptions.ClassDescription _ClassField;

/// <summary>
/// Access the Class parameter of the template.
/// </summary>
private global::ReCrafted.Tools.APIGenerator.Descriptions.ClassDescription Class
{
    get
    {
        return this._ClassField;
    }
}

private global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.FunctionDescription> _FunctionsField;

/// <summary>
/// Access the Functions parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.FunctionDescription> Functions
{
    get
    {
        return this._FunctionsField;
    }
}

private global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.PropertyDescription> _PropertiesField;

/// <summary>
/// Access the Properties parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.PropertyDescription> Properties
{
    get
    {
        return this._PropertiesField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ClassValueAcquired = false;
if (this.Session.ContainsKey("Class"))
{
    this._ClassField = ((global::ReCrafted.Tools.APIGenerator.Descriptions.ClassDescription)(this.Session["Class"]));
    ClassValueAcquired = true;
}
if ((ClassValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Class");
    if ((data != null))
    {
        this._ClassField = ((global::ReCrafted.Tools.APIGenerator.Descriptions.ClassDescription)(data));
    }
}
bool FunctionsValueAcquired = false;
if (this.Session.ContainsKey("Functions"))
{
    this._FunctionsField = ((global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.FunctionDescription>)(this.Session["Functions"]));
    FunctionsValueAcquired = true;
}
if ((FunctionsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Functions");
    if ((data != null))
    {
        this._FunctionsField = ((global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.FunctionDescription>)(data));
    }
}
bool PropertiesValueAcquired = false;
if (this.Session.ContainsKey("Properties"))
{
    this._PropertiesField = ((global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.PropertyDescription>)(this.Session["Properties"]));
    PropertiesValueAcquired = true;
}
if ((PropertiesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Properties");
    if ((data != null))
    {
        this._PropertiesField = ((global::System.Collections.Generic.List<ReCrafted.Tools.APIGenerator.Descriptions.PropertyDescription>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class CPlusPlusTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
