// ReCrafted (c) 2016-2018 Always Too Late

#pragma once

#ifndef RECRAFTEDCONFIG_H
#define RECRAFTEDCONFIG_H

#define COMPILE_WITH_GRAPHICS 1
#define COMPILE_WITH_PHYSICS 1

#if _DEBUG
#define COMPILE_WITH_RESOURCE_LISTING 1
#define USE_CRTDBG 1
#else
#define COMPILE_WITH_RESOURCE_LISTING 0
#define USE_CRTDBG 0
#endif

#endif // RECRAFTEDCONFIG_H
