// ReCrafted (c) 2016-2018 Always Too Late

#pragma once

#ifndef RECRAFTEDCONFIG_H
#define RECRAFTEDCONFIG_H

#define COMPILE_WITH_GRAPHICS 1
#define COMPILE_WITH_PHYSICS 1
#define COMPILE_WITH_WEBUI 1
#define COMPILE_WITH_RPMALLOC 1

#define USE_CRTDBG _DEBUG

#endif // RECRAFTEDCONFIG_H
