// ReCrafted © 2016-2017 Damian 'Erdroy' Korczowski and Mateusz 'Maturas' Zawistowski

#pragma once

#ifndef RECRAFTEDCONFIG_H
#define RECRAFTEDCONFIG_H

#define RECRAFTED_MAX_ITEMS (64 << 10)

#define RECRAFTED_BLOCK_ATLAS_SIZE 1024

#define RECRAFTED_BLOCK_ATLAS_ITEM_SIZE 32

#define RECRAFTED_BLOCK_SAMPLER_FLAGS 0 | BGFX_TEXTURE_RT | BGFX_TEXTURE_MIN_POINT | BGFX_TEXTURE_MAG_POINT | BGFX_TEXTURE_MIP_POINT | BGFX_TEXTURE_U_CLAMP | BGFX_TEXTURE_V_CLAMP

#define NEW_RENDERING 0

#endif // RECRAFTEDCONFIG_H
